// Generated by scripts/sync-data.mjs — do not edit.
import p0 from './absata.json';
import p1 from './balive.json';
import p2 from './briefly.json';
import p3 from './catalyst.json';
import p4 from './colab.json';
import p5 from './filmu.json';
import p6 from './haptic-wayfinder.json';
import p7 from './hisplora.json';
import p8 from './live-collab.json';
import p9 from './load-away.json';
import p10 from './logic-and-code.json';
import p11 from './meridian.json';
import p12 from './pelican.json';
import p13 from './popshot.json';
import p14 from './regulens.json';
import p15 from './shopify-automation.json';
import p16 from './suwotify.json';

const projects: unknown[] = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16];
export default projects;
