#!/usr/bin/env node
/**
 * Copy DATA-PORTO into this project.
 *
 * DATA-PORTO is the single source of truth for every word and picture on the
 * site, but it lives in its own repository — outside this project root, where
 * neither the bundler nor a deploy can reach it. So the data is vendored:
 *
 *   DATA-PORTO/data/**\/*.json  →  src/data/**\/*.json   (imported at build time)
 *   DATA-PORTO/assets/**        →  public/assets/**      (served at /assets/...)
 *
 * Asset paths in the data are already written as `assets/...`, so copying the
 * folder under public/ makes every path resolve with a leading slash and no
 * rewriting. Both targets are wiped first so a record deleted upstream does
 * not linger here.
 *
 *   npm run sync-data
 *   DATA_PORTO_DIR=/path/to/DATA-PORTO npm run sync-data
 */
import { cpSync, existsSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(process.env.DATA_PORTO_DIR ?? join(root, '../../../DATA-PORTO'));

if (!existsSync(join(source, 'data/index.json'))) {
  console.error(`sync-data: no DATA-PORTO at ${source} (set DATA_PORTO_DIR)`);
  process.exit(1);
}

const skip = (src) => !/(^|\/)(\.gitkeep|\.DS_Store)$/.test(src);

const targets = [
  { from: join(source, 'data'), to: join(root, 'src/data') },
  { from: join(source, 'assets'), to: join(root, 'public/assets') },
];

for (const { from, to } of targets) {
  rmSync(to, { recursive: true, force: true });
  cpSync(from, to, { recursive: true, filter: skip });
  console.log(`sync-data: ${from} → ${to}`);
}

// Projects are one file per record, and a bundler cannot glob a folder of
// JSON at build time. Write a barrel that imports each one, so a project added
// upstream appears here on the next sync without touching any code.
const projectsDir = join(root, 'src/data/projects');
const files = readdirSync(projectsDir)
  .filter((f) => f.endsWith('.json'))
  .sort();
const barrel = [
  '// Generated by scripts/sync-data.mjs — do not edit.',
  ...files.map((f, i) => `import p${i} from './${f}';`),
  '',
  `const projects: unknown[] = [${files.map((_, i) => `p${i}`).join(', ')}];`,
  'export default projects;',
  '',
].join('\n');
writeFileSync(join(projectsDir, 'index.ts'), barrel);
console.log(`sync-data: ${files.length} projects → src/data/projects/index.ts`);
